##### import libraries

In [3]:
import numpy as np
import pandas as pd

#### define array a

In [15]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
print(a.shape) #number of crows and columns
print(a.ndim)  #number of dimentions
print(a.size)  #number of numbers
print(type(b))

(15,)
1
15


#### change the dimentions of the array

In [41]:
a = a.reshape(3,5)

ValueError: cannot reshape array of size 15 into shape (3,3)

In [32]:
print(a.shape) #number of crows and columns
print(a.ndim)  #number of dimentions
print(a.size)  #number of numbers
print(type(b))

(3, 5)
2
15
<class 'numpy.ndarray'>


#### define second array

In [42]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
print(b.shape) #number of crows and columns
print(b.ndim)  #number of dimentions
print(b.size)  #number of numbers
print(type(b))

(3, 4)
2
12
<class 'numpy.ndarray'>


## now let's do math on a and b

In [50]:
a = np.arange(9).reshape(3, 3)


In [57]:
#Element-wise multiplication 
#(multiolies the numbers in a and b which have the identical adress)
a*b 

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [53]:
a@b #performs matrix multiplication

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [64]:
print("Exponential:", np.exp(a)) #calculate exponential of every element
print("Logarithmic:", np.log(a)) #calculate logarithm  of every element

Exponential: [[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]]
Logarithmic: [[      -inf 0.         0.69314718]
 [1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154]]


C:\Users\90536\AppData\Local\Temp\ipykernel_3808\345755663.py:2: RuntimeWarning: divide by zero encountered in log
  print("Logarithmic:", np.log(a)) #calculate logarithm  of every element


In [59]:
np.sin(a) #sinus value of every element of the matrix

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

### Generate a random array of shape (3, 3)y)

In [62]:
random_array = np.random.rand(3, 3)
random_array

array([[0.23087097, 0.02898656, 0.61354867],
       [0.00177759, 0.63399649, 0.41236348],
       [0.20873682, 0.46201713, 0.35607587]])

In [67]:
print(a)
# Square root of an array
sqrt_array = np.sqrt(a)
print(sqrt_array)

# Rounding elements of an array
rounded_array = np.round(sqrt_array, decimals=2)
print(rounded_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]
[[0.   1.   1.41]
 [1.73 2.   2.24]
 [2.45 2.65 2.83]]


In [68]:
np.random.rand(6,4)  #generated numbers are positive
np.random.randn(6,4) #generated numbers are near zero(including negative numbers)

array([[-0.66161811, -0.18267236, -0.53565792,  0.33615817],
       [ 1.63436794,  0.68463463,  0.07683006,  0.42876474],
       [-0.11189719,  1.75011375, -0.08404069, -1.25099155],
       [ 0.401662  ,  1.52588655, -0.84226075, -0.74647609],
       [-0.19708814,  0.8409187 , -0.453812  , -0.71455288],
       [-0.97486804,  0.94081573, -0.56453939,  0.63208163]])

### Generate random numbers in array

In [92]:


# Generate a random array of shape (3, 3)
random_array = np.random.rand(3, 3)
print("Random array:")
print(random_array)

# Generate random numbers from a normal distribution with mean 10 and standard deviation 5
random_normal = np.random.normal(10, 5, size=(2, 2))
print("Random numbers from a normal distribution:")
print(random_normal)

# Shuffle an array
original_array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(original_array)
print("Shuffled array:", original_array)

# Generate a random permutation of a sequence
permutation = np.random.permutation([1, 2, 3, 4, 5])
print("Random permutation:", permutation)

Random array:
[[0.0195897  0.58142523 0.93539552]
 [0.83289901 0.10860128 0.59434332]
 [0.96382686 0.26951951 0.90741055]]
Random numbers from a normal distribution:
[[13.89049156 12.29396542]
 [17.96332921 14.34647775]]
Shuffled array: [3 1 5 4 2]
Random permutation: [4 3 5 2 1]


### Indexing

In [99]:
# Accessing the element at row 1, column 2
print(a)
print(a[1, 2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5


#### Accessing specific elements of an array using indexing.

In [102]:
print(a)

# Accessing a single element
print("Element at row 1, column 2:", a[1, 2])

# Accessing a row
print("Row 1:", a[1])

# Accessing a column
print("Column 2:", a[:, 2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Element at row 1, column 2: 5
Row 1: [3 4 5]
Column 2: [2 5 8]


#### Let's filter elements

In [105]:
# Filter elements greater than 2
filtered_a = a[a > 2]
print("Elements greater than 2:", filtered_a)

# Use the boolean array to filter elements
a_less2 = a < 5
filtered_a = a[a_less2]
print("Elements less than 5:", filtered_a)

Elements greater than 2: [3 4 5 6 7 8]
Elements less than 5: [0 1 2 3 4]


### Average & Standart Deviation

##### Mean (Average)  The mean of a dataset is the average value of all the data points. (sum/quantity)
##### Standard Deviation: the spread or dispersion of the values around the mean. It quantifies the amount of variation or uncertainty in the dataset. A low standard deviation indicates that the data points tend to be close to the mean, while a high standard deviation indicates that the data points are spread out over a wider range of values.

In [106]:
print(a)
a_mean = np.mean(a)
a_deviation = np.std(a)
print("Mean:", a_mean)
print("Standard Deviation:", a_deviation)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Mean: 4.0
Standard Deviation: 2.581988897471611


#### Aggregation

In [111]:
# Normal sum
print(a)
a_sum = np.sum(a)
print("Total Sum:", a_sum)

# row-wise sum
a_row_sum = np.sum(a, axis=1)
print("Row-wise Sum:", a_row_sum)

# column-wise sum
a_col_sum = np.sum(a, axis=0)
print("Column-wise Sum:", a_col_sum)

#min & max
max_value = np.max(a)
min_value = np.min(a)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)

# Find unique values and counts
unique_values, counts = np.unique(a, return_counts=True)
print("Unique Values:", unique_values)
print("Counts:", counts)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Total Sum: 36
Row-wise Sum: [ 3 12 21]
Column-wise Sum: [ 9 12 15]
Maximum Value: 8
Minimum Value: 0
Unique Values: [0 1 2 3 4 5 6 7 8]
Counts: [1 1 1 1 1 1 1 1 1]
